networks:
  the:


services:
  server:
    build:
      context: .
    ports:
      - 9000:80
    depends_on:
      - db
    networks:
      - the
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'billybob'
      MYSQL_ROOT_PASSWORD: 'billybob'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./table_setup.sql:/tmp/database/table_setup.sql
    command: --init-file="/tmp/database/table_setup.sql"
    networks:
      - the
volumes:
  my-db:
